'use client';
import {useEffect,useState} from 'react';
import Feed from './feed';
import type {Listing} from '@/lib/feed-parser';
import {Plus,Link,ArrowUpRight,Check,Inbox,CalendarDays,LayoutGrid,LockKeyhole,CheckCheck,ArrowRight,Link2,ClipboardList,Package,MapPin,Search} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {Campaign,statuses,platforms,dueLabel} from '@/lib/model';
import {listCampaigns,saveCampaign,toggleTask} from './actions';
import Connect29CM from './connect-29cm';
const blank=():Campaign=>({id:'',title:'',platform:'레뷰',url:'',kind:'배송형',status:'관심',due:'',notes:'',tasks:[],created:''});
function Choice({value,values,onChange,label}:{value:string;values:string[];onChange:(v:string)=>void;label:string}){return <Select value={value} onValueChange={v=>v&&onChange(v)}><SelectTrigger aria-label={label} className="choice"><SelectValue/></SelectTrigger><SelectContent>{values.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select>}
export default function Desk(){
 const [records,setRecords]=useState<Campaign[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[tab,setTab]=useState('discover'),[filter,setFilter]=useState('전체'),[search,setSearch]=useState(''),[draft,setDraft]=useState<Campaign|null>(null),[busy,setBusy]=useState(false),[formError,setFormError]=useState(''),[connecting,setConnecting]=useState(false);
 async function refresh(){try{setRecords(await listCampaigns());setError('');}catch(e){setError(e instanceof Error?e.message:'저장된 내용을 불러오지 못했습니다.');}finally{setLoading(false);}}
 useEffect(()=>{refresh()},[]);
 const won=records.filter(r=>r.status==='당첨'),applied=records.filter(r=>r.status==='신청 완료'),done=records.filter(r=>r.status==='완료');
 const ordered=[...won].sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999'));
 const count=won.reduce((n,r)=>n+r.tasks.filter(t=>!t.done).length,0);
 const visible=records.filter(r=>(filter==='전체'||r.status===filter)&&`${r.title} ${r.platform}`.toLowerCase().includes(search.toLowerCase()));
 const edit=(r:Campaign)=>{setFormError('');setDraft({...r})};
 async function submit(e:React.FormEvent){e.preventDefault();if(!draft||busy)return;setBusy(true);setFormError('');try{await saveCampaign(draft);setDraft(null);setNotice('체험단을 저장했어요.');await refresh();}catch(e){setFormError(e instanceof Error?e.message:'저장에 실패했습니다. 다시 시도해 주세요.');}finally{setBusy(false)}}
 async function tick(r:Campaign,id:string,checked:boolean){if(busy)return;setBusy(true);try{await toggleTask(r.id,id,checked);await refresh();setNotice(checked?'할 일을 완료했어요.':'완료 표시를 취소했어요.')}catch(e){setError(e instanceof Error?e.message:'변경에 실패했습니다.')}finally{setBusy(false)}}
 async function finish(r:Campaign){if(busy)return;setBusy(true);try{await saveCampaign({...r,status:'완료'});await refresh();setNotice('체험단을 완료했어요. 수고하셨습니다!')}catch(e){setError(e instanceof Error?e.message:'변경에 실패했습니다.')}finally{setBusy(false)}}
 async function collect(r:Listing,status:string){if(busy)return false;const existing=records.find(v=>v.url===r.url);if(existing&&status!=='신청 완료'){setNotice('이미 내 신청함에 저장되어 있어요.');return true;}setBusy(true);try{if(existing){if(existing.status==='관심')await saveCampaign({...existing,status});}else await saveCampaign({...blank(),title:r.title.slice(0,150),platform:platforms.includes(r.platform)?r.platform:'기타',url:r.url,kind:('kind' in r?String(r.kind):r.title.includes('배송')?'배송형':'기타'),status,notes:'공고 출처: '+r.platform+' · '+r.channel+'\n모집 마감 안내: '+r.deadline+'\n리뷰 마감일은 당첨 후 원문에서 확인해 주세요.'});await refresh();setNotice(status==='관심'?'관심 체험단으로 담았어요.':'신청 완료로 기록했어요.');return true;}catch(e){setError(e instanceof Error?e.message:'저장에 실패했습니다.');return false;}finally{setBusy(false)}}
 return <main className={"shell "+(tab==='discover'?'discovery-shell':'')}><header className="top"><a className="logo" href="./">moaview<span>모아뷰</span></a><div className="top-right"><button className="link-29cm" onClick={()=>setConnecting(true)}><Link size={14}/> 29CM 연결</button><span className="private"><LockKeyhole size={14}/> 나의 체험 보관함</span></div></header>{connecting&&<Connect29CM onClose={()=>setConnecting(false)} onDone={refresh}/>}
 {tab!=='discover'&&<><section className="intro intro-row"><div><p className="eyebrow">MY REVIEW DESK</p><h1>새로운 체험을 발견하는 곳.</h1><p>흩어진 체험단을 둘러보고, 신청부터 리뷰까지 한곳에서.</p></div><button className="outline add" onClick={()=>setTab("tasks")}><ClipboardList size={17}/> 나의 할 일 <span className="tab-count">{count}</span></button></section>
 <section className="stats" aria-label="체험단 현황">{[[Inbox,'신청 후 기다리는 중',applied.length,'건'],[CheckCheck,'당첨된 체험단',won.length,'건'],[ClipboardList,'남은 할 일',count,'개'],[Check,'리뷰까지 완료',done.length,'건']].map(([Icon,label,n,unit]:any,i)=><div key={label} className={'stat stat-'+i}><span className="stat-label"><Icon size={17}/>{label}</span><div><strong>{loading?'—':n}</strong><span>{unit}</span></div></div>)}</section></>}
 {error&&<div className="message error" role="alert">{error}<button onClick={()=>{setLoading(true);refresh()}}>다시 불러오기</button></div>}
 {notice&&<div className="message" role="status">{notice}<button aria-label="알림 닫기" onClick={()=>setNotice('')}>닫기</button></div>}
 <div className="workspace"><section className="main-column"><Tabs value={tab} onValueChange={v=>setTab(String(v))}><TabsList className="nav-tabs" variant="line"><TabsTrigger value="discover"><Search/>체험단 둘러보기</TabsTrigger><TabsTrigger value="tasks"><ClipboardList/>해야 할 일 <span className="tab-count">{count}</span></TabsTrigger><TabsTrigger value="applications"><LayoutGrid/>신청 관리</TabsTrigger></TabsList>
 <TabsContent value="tasks"><div className="section-heading"><h2>이번 체험, 차근차근</h2><span>마감일 빠른 순</span></div>{loading?<div className="panel waiting">나의 체험단을 불러오고 있어요.</div>:ordered.length?ordered.map(r=><article key={r.id} className="task-card"><div className="card-heading"><div><span className="overline">{r.platform} <span>· {r.kind}</span></span><h3>{r.title}</h3></div><span className={'due '+(dueLabel(r.due).includes('지남')||dueLabel(r.due)==='오늘 마감'?'urgent':'')}>{dueLabel(r.due)}</span></div><div className="deadline"><CalendarDays size={15}/>{r.due?`리뷰 마감 ${r.due.replaceAll('-','. ')}`:'리뷰 마감일을 등록해 주세요'}<button onClick={()=>edit(r)}>수정</button></div><div className="checklist">{r.tasks.map(t=><label key={t.id} className={t.done?'task checked':'task'}><Checkbox checked={t.done} onCheckedChange={c=>tick(r,t.id,!!c)} disabled={busy}/><span>{t.title}</span></label>)}</div>{r.notes&&<p className="notes">{r.notes}</p>}<div className="card-footer"><span>{r.tasks.filter(t=>t.done).length}/{r.tasks.length} 완료</span>{r.tasks.every(t=>t.done)?<button className="small-primary" disabled={busy} onClick={()=>finish(r)}>체험단 완료하기 <Check size={15}/></button>:r.url?<a href={r.url} target="_blank" rel="noopener noreferrer">공고·가이드 확인 <ArrowUpRight size={15}/></a>:null}</div></article>):<div className="welcome panel"><Empty><EmptyHeader><div className="empty-symbol"><ClipboardList size={30} strokeWidth={1.5}/></div><EmptyTitle>다음 체험을 기다리는 중이에요</EmptyTitle><EmptyDescription>목록에서 신청한 체험단을 담고 ‘당첨’으로 변경하면<br/>제품 수령부터 리뷰 제출까지 할 일이 생겨요.</EmptyDescription></EmptyHeader><button className="primary" onClick={()=>setTab("discover")}>체험단 둘러보기 <ArrowRight size={16}/></button></Empty><div className="steps"><span><i>01</i>신청 기록</span><ArrowRight size={14}/><span><i>02</i>당첨 확인</span><ArrowRight size={14}/><span><i>03</i>리뷰 완료</span></div></div>}</TabsContent>
 <TabsContent value="applications"><div className="section-heading"><h2>모아둔 체험단 <span>{records.length}</span></h2></div><div className="filters"><label className="search"><Search size={17}/><input aria-label="체험단 검색" placeholder="체험단 이름, 플랫폼 검색" value={search} onChange={e=>setSearch(e.target.value)}/></label><Choice value={filter} values={['전체',...statuses]} onChange={setFilter} label="신청 상태 필터"/></div>{loading?<div className="panel waiting">불러오는 중이에요.</div>:visible.length?<div className="record-list">{visible.map(r=><article key={r.id} className="record"><div className="kind-icon">{r.kind==='방문형'?<MapPin size={20}/>:<Package size={20}/>}</div><div className="record-info"><span className="overline">{r.platform} · {r.kind}</span><h3>{r.title}</h3><p>{r.due?`리뷰 마감 ${r.due}`:'마감일 미정'}</p></div><span className={'status '+(r.status==='당첨'?'blue':'')}>{r.status}</span><button className="outline" onClick={()=>edit(r)}>관리</button></article>)}</div>:<div className="panel"><Empty><EmptyHeader><EmptyTitle>{search||filter!=='전체'?'검색 결과가 없어요':'아직 등록한 체험단이 없어요'}</EmptyTitle><EmptyDescription>목록에서 관심 있거나 신청한 체험단을 담아주세요.</EmptyDescription></EmptyHeader><button className="primary" onClick={()=>setTab("discover")}>체험단 둘러보기</button></Empty></div>}</TabsContent>
 <TabsContent value="discover"><Feed onSave={collect} saved={records.map(r=>r.url)} applied={records.filter(r=>r.status!=='관심').map(r=>r.url)}/></TabsContent></Tabs></section>
 {tab!=='discover'&&<aside><div className="schedule panel"><div className="aside-heading"><CalendarDays size={19}/><h2>다가오는 마감</h2></div>{ordered.filter(r=>r.due).length?ordered.filter(r=>r.due).slice(0,5).map(r=><button className="deadline-item" key={r.id} onClick={()=>edit(r)}><span className="date-square">{r.due.slice(5,7)}<strong>{r.due.slice(8)}</strong></span><span><b>{r.title}</b><small>{dueLabel(r.due)}</small></span></button>):<div className="no-deadline"><span className="calendar-day">—</span><p>등록된 리뷰 마감이 없어요.</p><small>당첨된 체험단에 마감일을 넣으면<br/>여기서 빠르게 확인할 수 있어요.</small></div>}</div><div className="note-card"><span className="eyebrow">A LITTLE REMINDER</span><h3>당첨 후, 이것부터.</h3><ol><li>공고의 필수 키워드 확인</li><li>사진·영상 개수 확인</li><li>리뷰 마감일 등록</li></ol><p>플랫폼마다 미션이 달라요.<br/>원문 가이드를 꼭 확인해 주세요.</p></div><p className="privacy-note"><LockKeyhole size={12}/> 나의 기록은 나에게만 보여요.</p></aside>}</div><footer>moaview <span>나의 체험을 차곡차곡.</span></footer>
 <Dialog open={!!draft} onOpenChange={open=>{if(!open&&!busy)setDraft(null)}}><DialogContent className="campaign-dialog"><DialogTitle>{draft?.id?'체험단 관리':'새 체험단 등록'}</DialogTitle><DialogDescription>공고 내용과 신청 상태를 기록해 주세요.</DialogDescription>{draft&&<form onSubmit={submit} className="campaign-form"><label>체험단 이름 <span>*</span><input autoFocus required maxLength={150} placeholder="예: 수분 크림 블로그 체험단" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><div className="form-row"><label>플랫폼<Choice value={draft.platform} values={platforms} label="플랫폼" onChange={v=>setDraft({...draft,platform:v})}/></label><label>체험 유형<Choice value={draft.kind} values={['배송형','방문형','기타']} label="체험 유형" onChange={v=>setDraft({...draft,kind:v})}/></label></div><label>공고 링크<input type="url" maxLength={2000} placeholder="https://" value={draft.url} onChange={e=>setDraft({...draft,url:e.target.value})}/></label><div className="form-row"><label>신청 상태<Choice value={draft.status} values={statuses} label="신청 상태" onChange={v=>setDraft({...draft,status:v})}/></label><label>리뷰 마감일<input type="date" value={draft.due} onChange={e=>setDraft({...draft,due:e.target.value})}/></label></div><label>미션·메모<textarea rows={3} maxLength={5000} placeholder="필수 키워드, 사진 개수, 방문 일정 등을 남겨요." value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label><p className="form-hint">‘당첨’으로 저장하면 할 일이 자동으로 만들어져요. 이곳의 상태 변경은 원본 사이트에 반영되지 않습니다.</p>{formError&&<p className="form-error" role="alert">{formError}</p>}<div className="form-actions">{draft.url&&/^https?:\/\//.test(draft.url)&&<a href={draft.url} target="_blank" rel="noopener noreferrer">원문 열기 <ArrowUpRight size={15}/></a>}<button type="button" className="outline" disabled={busy} onClick={()=>setDraft(null)}>취소</button><button className="primary" disabled={busy} type="submit">{busy?'저장 중…':'저장하기'}</button></div></form>}</DialogContent></Dialog>
 </main>
}
