import {filterFeed} from '@/lib/filter-feed';
'use client';
import {useEffect,useState} from 'react';
import CampaignLink from './campaign-link';
import {Search,ArrowUpRight,Bookmark,RefreshCw,MapPin,Package,SlidersHorizontal,ArrowRight} from 'lucide-react';
import {categoryOptions,categoryLabel} from '@/lib/categories';
import type {Listing} from '@/lib/feed-parser';
import type {DirectListing,SourceState} from '@/lib/direct-feed';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
type Data={items:DirectListing[];total:number;sources:SourceState[];counts:Record<string,number>;updatedAt:string};
export default function Feed({onSave,saved,applied}:{onSave:(r:Listing,status:string)=>Promise<boolean|void>;saved:string[];applied:string[]}){
 const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[kind,setKind]=useState('delivery'),[category,setCategory]=useState('style'),[source,setSource]=useState('29CM'),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[sort,setSort]=useState('deadline'),[reload,setReload]=useState(0),[limit,setLimit]=useState(18);
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');setLimit(18);fetch(import.meta.env.BASE_URL+'data/feed.json',{signal:c.signal,cache:'no-cache'}).then(async r=>{if(!r.ok)throw Error('공고를 불러오지 못했어요.');setData(filterFeed(await r.json(),new URLSearchParams({kind,category,source,search,sort})))}).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort()},[kind,category,source,search,sort,reload]);
 const isApplied=(url:string)=>applied.includes(url);
 const connected=data?.sources.filter(s=>s.status==='ok')||[];
 return <section className="feed"><div className="catalog-heading"><div><span className="catalog-kicker">FOR YOUR NEXT REVIEW</span><h1>취향에 맞는 제품 체험<span>.</span></h1><p>뷰티와 패션부터 골라보세요. 전국 배송형을 먼저 보여드려요. 29CM 체험단부터 모아뒀어요.</p></div><div className="catalog-scope"><span><MapPin size={15}/> 서울 방문</span><span><Package size={15}/> 전국 배송</span></div></div>
 <form className="catalog-search" onSubmit={e=>{e.preventDefault();setSearch(query)}}><Search size={21}/><input aria-label="체험단 검색" placeholder="어떤 체험을 찾고 있나요?" value={query} onChange={e=>setQuery(e.target.value)} maxLength={100}/><button type="submit">검색 <ArrowRight size={17}/></button></form>
 <div className="catalog-controls"><Tabs value={kind} onValueChange={v=>setKind(String(v))}><TabsList className="kind-tabs">{[['delivery','전국 배송'],['visit','서울 방문'],['all','전체']].map(([v,t])=><TabsTrigger key={v} value={v}>{t}</TabsTrigger>)}</TabsList></Tabs><div className="catalog-selects"><span className="blog-only">{source==='29CM'?'29CM 체험단':'블로그 · 제품 체험단'}</span></div></div>
 <div className="platform-filter"><span className="filter-label">사이트</span><Tabs value={source||'all-sites'} onValueChange={v=>setSource(v==='all-sites'?'':String(v))}><TabsList className="platform-tabs" aria-label="체험단 사이트"><TabsTrigger value="all-sites">전체 사이트</TabsTrigger>{(data?.sources||[{name:'29CM',status:'ok'}]).map(s=><TabsTrigger key={s.name} value={s.name}>{s.name}{s.status==='error'&&<span className="platform-error">조회 실패</span>}</TabsTrigger>)}</TabsList></Tabs></div>
 <Tabs value={category} onValueChange={v=>setCategory(String(v))}><TabsList className="category-tabs" aria-label="상품 카테고리">{categoryOptions.map(([id,label])=><TabsTrigger value={id} key={id}>{label}{!loading&&data&&<span>{data.counts[id]||0}</span>}</TabsTrigger>)}</TabsList></Tabs>
 <p className="application-guide">각 사이트에서 신청한 뒤 돌아와 ‘신청 완료로 표시’를 눌러주세요.</p>
 <div className="catalog-results"><span>{loading?'공고를 가져오고 있어요':<>지금 모아온 체험 <b>{data?.total.toLocaleString()||0}</b></>}</span><div><Select value={sort} onValueChange={v=>setSort(v||'deadline')}><SelectTrigger aria-label="정렬"><SelectValue>{sort==='deadline'?'마감 가까운 순':'경쟁률 낮은 순'}</SelectValue></SelectTrigger><SelectContent><SelectItem value="deadline">마감 가까운 순</SelectItem><SelectItem value="competition">경쟁률 낮은 순</SelectItem></SelectContent></Select><button className="refresh" aria-label="공고 새로고침" disabled={loading} onClick={()=>setReload(v=>v+1)}><RefreshCw size={16}/></button></div></div>
 {error?<div className="catalog-empty" role="alert">{error}<button onClick={()=>setReload(v=>v+1)}>다시 불러오기</button></div>:loading?<div className="catalog-grid" role="status" aria-label="공고 불러오는 중">{[1,2,3].map(n=><div key={n} className="catalog-skeleton"><div/><span/><span/></div>)}</div>:!data?.items.length?<div className="catalog-empty"><Search size={28}/><h2>조건에 맞는 공고가 없어요</h2><p>연결된 공개 목록 안에서 검색하고 있어요. 검색어나 필터를 바꿔보세요.</p></div>:<div className="catalog-grid">{data.items.slice(0,limit).map(r=><article className="experience-card" key={r.id}><div className="experience-image"><a href={r.url} target="_blank" rel="noopener noreferrer" aria-label={r.name+' 공고 보기'}>{r.image?<img src={r.image} alt={r.name} loading="lazy" referrerPolicy="no-referrer" onError={e=>{e.currentTarget.style.display='none'}}/>:<span className="image-unavailable">{r.kind==='배송형'?<Package size={30}/>:<MapPin size={30}/>}공고 사진 미제공</span>}</a><span className="deadline-pill">{r.deadline}</span><button className="image-save" disabled={saved.includes(r.url)} onClick={()=>onSave(r,'관심')} aria-label={r.name+' 관심 저장'}><Bookmark size={18} fill={saved.includes(r.url)?'currentColor':'none'}/></button></div><div className="experience-body"><div className="experience-meta"><span>{r.platform} · {categoryLabel[r.category]}</span><span>{r.kind==='배송형'?'배송형':r.region}</span></div><h3><a href={r.url} target="_blank" rel="noopener noreferrer">{r.name}</a></h3><p className="experience-benefit" title={r.benefit}>{r.benefit||'제공 내역은 원문에서 확인해 주세요.'}</p><details className="experience-details"><summary>참여 조건 확인</summary><p>{r.title}</p><p>{r.conditions}</p><small>{r.categoryOrigin==='source'?'원본 사이트 카테고리':'제목·제공 내역을 기준으로 분류'}</small>{r.kind==='배송형'&&<p>배송 가능 지역·추가 배송비는 원문을 확인해 주세요.</p>}</details><div className="experience-bottom"><span>신청 <b>{r.applicants??'—'}</b><i>/</i>모집 <b>{r.recruits??'—'}</b></span>{isApplied(r.url)?<span className="applied-badge">✓ 신청 완료</span>:<CampaignLink url={r.url} platform={r.platform}/>}</div>{!isApplied(r.url)&&<button className="record-applied" onClick={()=>onSave(r,'신청 완료')}>신청 완료로 표시</button>}</div></article>)}</div>}
 {!loading&&data&&limit<data.items.length&&<button className="catalog-more" onClick={()=>setLimit(n=>n+18)}>체험단 더 보기 <span>{Math.min(limit,data.total)} / {data.total}</span></button>}
 <p className="collection-stamp">원본 사이트에서 가져온 공고{data&&<> · {new Date(data.updatedAt).toLocaleTimeString('ko-KR',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit'})} 수집</>} · 6시간마다 갱신 · 일부 공개 목록</p>
 <details className="connection-details"><summary><span><i/>원본 사이트 연결 현황 <b>{connected.length}개 조회</b></span><span>자세히 보기</span></summary><p>각 사이트에서 직접 읽은 공개 모집 공고입니다. 원문에서 모집 상태를 최종 확인해 주세요.</p><div className="connections-grid">{data?.sources.map(s=><div key={s.name}><strong>{s.name}</strong><span className={'connection-'+s.status}>{s.status==='ok'?`${s.count}개 조회`:'조회 실패'}</span><small>{s.scope}</small></div>)}</div>{data&&<small>{new Date(data.updatedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})} 수집</small>}</details>
 </section>
}
