import {twentynine} from './twentynine';
import {classify,type Category} from './categories';
import type {Listing} from './feed-parser';
export type SourceState={name:string;url:string;status:'ok'|'error';count:number;scope:string};
export type DirectListing=Listing&{image?:string;kind:'배송형'|'방문형';endAt?:string;category:Category;categoryOrigin:'source'|'summary'};
const text=(v:unknown)=>String(v??'').replace(/<script[\s\S]*?<\/script>/g,'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&gt;/g,'>').replace(/&lt;/g,'<').replace(/&nbsp;/g,' ').replace(/&quot;/g,'"').replace(/\s+/g,' ').trim();
const get=(s:string,re:RegExp)=>text(s.match(re)?.[1]);
const seoul=/^서울(?:\s|\/|$|특별시)/;
const localSeoul=/^(삼성역|강남역|잠실|합정|연남|성수|홍대|선릉|역삼|신촌|여의도|종로|한남|이태원|신당|건대|망원|서초|사당|마곡|목동|노원|성신여대|서울대입구)(?:\s|$)/;
function entry(platform:string,url:string,title:string,region:string,benefit:string,deadline:string,image:string,applicants:number|null,recruits:number|null,delivery=false):DirectListing|null{
 if(!deadline||/종료|마감완료|선정완료/.test(deadline))return null;
 if(!delivery&&!seoul.test(region)&&!localSeoul.test(region))return null;
 return {category:classify(title,benefit),categoryOrigin:'summary',id:platform+':'+url,platform,url,title,name:title.replace(/^\[[^\]]+\]\s*/,''),region:delivery?'전국 배송':seoul.test(region)?region:'서울 · '+region,benefit,conditions:'상세 미션·이용 조건은 원문에서 확인해 주세요.',deadline,channel:'블로그',applicants,recruits,image:/^https:\/\//.test(image)?image:undefined,kind:delivery?'배송형':'방문형'};
}
export function reviewnote(html:string):DirectListing[]{const match=html.match(/<script id="__NEXT_DATA__" type="application\/json">([\s\S]*?)<\/script>/);if(!match)throw Error('목록 형식 확인 필요');const data=JSON.parse(match[1]).props.pageProps.data;const images=[...html.matchAll(/src="([^"]+)"/g)].map(m=>text(m[1]));return (data.objects as any[]).flatMap(x=>{if(x.channel!=='BLOG'||!['SELECT','APPLY'].includes(x.status)||Date.parse(x.applyEndAt)<Date.now())return [];const delivery=x.sort==='DELIVERY';if(delivery&&/보험|컨설팅|상담사 출장|물품 배송x|포인트만/.test(x.offer))return [];const region=x.city+' '+(x.sido?.name||'');const days=Math.max(0,Math.ceil((Date.parse(x.applyEndAt)-Date.now())/86400000));const image=images.find(u=>u.includes(encodeURIComponent(x.imageKey)))||'';const r=entry('리뷰노트','https://www.reviewnote.co.kr/campaigns/'+x.id,x.title,region,text(x.offer),days===0?'오늘 마감':`D-${days}`,image,x.applicantCount,x.infNum,delivery);if(r&&['뷰티','패션','식품','생활','리빙'].includes(x.category?.title)){r.category=({'뷰티':'beauty','패션':'fashion','식품':'food','생활':'living','리빙':'living'} as Record<string,Category>)[x.category.title];r.categoryOrigin='source';}if(r&&/지역.*참여|지역.*가능/.test(x.title)){r.region='배송형 · 지역 제한';r.conditions=x.title;}return r?[{...r,endAt:x.applyEndAt}]:[]});}
export function mible(html:string):DirectListing[]{return [...html.matchAll(/<a href="([^"]+)" class="campaign_item">([\s\S]*?)<\/a>/g)].flatMap(m=>{const s=m[2];if(!/sns_icon blog/.test(s))return [];const region=get(s,/class="area">([\s\S]*?)<\/span>\s*<strong/);const r=entry('미블',m[1],get(s,/class="subject">([\s\S]*?)<\/strong>/),region,get(s,/class="desc">([\s\S]*?)<\/p>/),get(s,/class="d_day">([\s\S]*?)<\/span>/),get(s,/<img src="([^"]+)"/),Number(get(s,/신청\s*<strong>(\d+)/)),Number(get(s,/모집\s*(\d+)/)),region.includes('배송'));return r?[r]:[]});}
export function play(html:string):DirectListing[]{return [...html.matchAll(/<li>([\s\S]*?)<\/li>/g)].flatMap(m=>{const s=m[1];if(!/class="blog"/.test(s))return [];const path=get(s,/href="(item.php\?it_id=[^"]+)"/);if(!path)return [];const title=get(s,/class="it_name">([\s\S]*?)<\/span>/);const region=title.match(/^\[([^\]]+)\]/)?.[1]||'';const image=get(s,/<img src="([^"]+)"[^>]*class="it_img"/);const r=entry('놀러와체험단',new URL(path,'https://cometoplay.kr/').href,title,region,get(s,/class="it_description">([\s\S]*?)<\/span>/),get(s,/class="txt_num">(D-day\s*\d+)/),image?new URL(image,'https://cometoplay.kr/').href:'',Number(get(s,/신청\s*<b[^>]*>(\d+)/)),Number(get(s,/모집\s*<b[^>]*>(\d+)/)),/배송|쇼핑몰/.test(region));return r?[r]:[]});}
export function ouba(html:string):DirectListing[]{return html.split('<li class="campaign_content">').slice(1).flatMap(block=>{const s=block.split('</li>')[0];if(!/thum_ch_blog/.test(s))return [];const title=get(s,/class="s_campaign_title">([\s\S]*?)<\/strong>/);const region=title.match(/^\[([^\]]+)\]/)?.[1]||'';const r=entry('서울오빠',get(s,/href="([^"]+)"[^>]*class="tum_img"/),title,region,get(s,/class="basic_blue">([\s\S]*?)<\/span>/),get(s,/class="d_day"><span>([\s\S]*?)<\/span>/),get(s,/<img src="([^"]+)"/),Number(get(s,/신청\s*(\d+)/)),Number(get(s,/모집\s*(\d+)/)),region.includes('배송'));return r?[r]:[]});}
type Provider={name:string;url:string;parse:(s:string)=>DirectListing[];scope:string;extras?:{url:string;category?:Category}[]};
// 강남맛집은 파서가 동작하지만 GitHub Actions의 해외 IP를 막아 목록에서 제외했다.
const API29='https://preuser-api.29cm.co.kr/api/v4/preuser/events';
const providers:Provider[]=[{name:'29CM',url:API29+'?page=1&size=100',parse:twentynine,scope:'모집 중인 29CM 체험단 전체',extras:[{url:API29+'?page=2&size=100'}]}, {name:'아싸뷰',url:'https://assaview.co.kr/',parse:assa,scope:'홈 공개 모집 공고'}, {name:'리뷰노트',url:'https://www.reviewnote.co.kr/campaigns',parse:reviewnote,scope:'공개 목록에 제공되는 공고'}, {name:'미블',url:'https://www.mrblog.net/',parse:mible,scope:'홈 공개 공고 · 전체 목록은 로그인 필요'}, {name:'놀러와체험단',url:'https://cometoplay.kr/index.php',parse:play,scope:'홈 공개 모집 공고'}, {name:'서울오빠',url:'https://www.seoulouba.co.kr/campaign/',parse:ouba,scope:'공개 모집 목록 첫 페이지'}];
let cached:{at:number;items:DirectListing[];sources:SourceState[]}|undefined;
export async function directFeed(){
 if(cached&&Date.now()-cached.at<300000)return cached;
 const results=await Promise.all(providers.map(async p=>{
  const pages=await Promise.allSettled([{url:p.url,category:undefined as Category|undefined},...(p.extras||[])].map(async page=>{const r=await fetch(page.url,{signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error();const html=await r.text();const items=p.parse(html);return page.category?items.map(item=>({...item,category:page.category!,categoryOrigin:'source' as const})):items;}));
  const successes=pages.filter((r):r is PromiseFulfilledResult<DirectListing[]>=>r.status==='fulfilled');const items=[...new Map(successes.flatMap(r=>r.value).map(r=>[r.url,r])).values()];const failed=pages.length-successes.length;
  return {items,source:{name:p.name,url:p.url,status:successes.length?'ok' as const:'error' as const,count:items.length,scope:successes.length?p.scope+(failed?' · 일부 목록 조회 실패':''):'현재 불러오지 못함 · 재시도 필요'}};
 }));
 const items=[...new Map(results.flatMap(r=>r.items).map(r=>[r.url,r])).values()];cached={at:Date.now(),items,sources:[...results.map(r=>r.source)]};return cached;
}
export function gangnam(html:string):DirectListing[]{return [...html.matchAll(/<li class='list_item[^']*'[^>]*>([\s\S]*?)<\/li>/g)].flatMap(m=>{const s=m[1];if(!/class='blog'/.test(s))return [];const title=get(s,/class='tit'><a[^>]*>([\s\S]*?)<\/a>/);const path=get(s,/href='([^']+)'/);const region=title.match(/^\[([^\]]+)\]/)?.[1]||'';const image=get(s,/<img src='([^']+)'/);const flat=text(s);const r=entry('강남맛집',new URL(path,'https://xn--939au0g4vj8sq.net/').href,title,region,get(s,/class='sub_tit'>([\s\S]*?)<\/dd>/),get(s,/class='day_c'>([\s\S]*?)<\/em>/),image?new URL(image,'https://xn--939au0g4vj8sq.net/').href:'',Number(flat.match(/신청\s*([\d,]+)/)?.[1].replaceAll(',','')||0),Number(flat.match(/모집\s*([\d,]+)/)?.[1].replaceAll(',','')||0),/class='type'>배송형/.test(s));if(r&&/페이백/.test(title))r.conditions='페이백 공고 · 구매 비용과 환급 조건을 원문에서 확인해 주세요.';return r?[r]:[]});}
export function assa(html:string):DirectListing[]{return [...html.matchAll(/<a href="(campaign.php\?cp_id=[^"]+)">([\s\S]*?)<\/a>/g)].flatMap(m=>{const s=m[2];if(!/blog_icon/.test(s))return [];const title=get(s,/class="subject">([\s\S]*?)<\/div>/);const region=title.match(/^\[([^\]]+)\]/)?.[1]||'';const until=get(s,/data-countdown\d?="([^"]+)"/);if(!until)return [];const end=until.replaceAll('/','-').replace(' ','T')+'+09:00';if(Date.parse(end)<Date.now())return [];const days=Math.ceil((Date.parse(end)-Date.now())/86400000);const image=get(s,/<img src="([^"]+)"/);const flat=text(s);const delivery=/배송형|구매형/.test(get(s,/class="cp_type">([\s\S]*?)<\/div>/));const r=entry('아싸뷰',new URL(m[1],'https://assaview.co.kr/').href,title,region,get(s,/class="opt_name">([\s\S]*?)<\/span>/),`D-${days}`,image?new URL(image,'https://assaview.co.kr/').href:'',Number(flat.match(/신청\s*(\d+)/)?.[1]||0),Number(flat.match(/\/\s*(\d+)명/)?.[1]||0),delivery);if(r){r.endAt=end;if(/구매형/.test(s))r.conditions='구매형 공고 · 선결제 금액과 환급 조건을 원문에서 확인해 주세요.';}return r?[r]:[]});}
